version: 2
project_name: debtdrone

builds:
  - id: debtdrone-cli
    dir: .
    main: ./cmd/debtdrone
    binary: debtdrone
    env:
      - CGO_ENABLED=1
      - CC={{ if eq .Os "darwin" }}{{ if eq .Arch "amd64" }}o64-clang{{ else }}oa64-clang{{ end }}{{ else if eq .Os "linux" }}{{ if eq .Arch "amd64" }}x86_64-linux-gnu-gcc{{ else }}aarch64-linux-gnu-gcc{{ end }}{{ end }}
      - CXX={{ if eq .Os "darwin" }}{{ if eq .Arch "amd64" }}o64-clang++{{ else }}oa64-clang++{{ end }}{{ else if eq .Os "linux" }}{{ if eq .Arch "amd64" }}x86_64-linux-gnu-g++{{ else }}aarch64-linux-gnu-g++{{ end }}{{ end }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "386" }}i386{{ else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "README"
      - "Merge pull request"
      - "Merge branch"
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance Improvements"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Other Changes"
      order: 999

release:
  github:
    owner: endrilickollari
    name: debtdrone-cli
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## DebtDrone CLI {{ .Tag }}

    **Stop counting lines. Start fixing debt.**

    ### Installation

    ```bash
    curl -sL https://raw.githubusercontent.com/endrilickollari/debtdrone-cli/main/install.sh | bash
    ```

    Or download the binary for your platform below.
  footer: |
    ---
    **Full Changelog**: https://github.com/endrilickollari/debtdrone-cli/compare/{{ .PreviousTag }}...{{ .Tag }}

announce:
  skip: true
