package analysis

import (
	"bufio"
	"context"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/endrilickollari/debtdrone-cli/internal/git"
	"github.com/go-git/go-billy/v5"
)

const (
	MaxFileSize   = 10 * 1024 * 1024 // 10 MB - increased for cloud SaaS
	MaxLineCount  = 100000           // 100k lines max - increased for cloud SaaS
	MaxLineLength = 10000            // 10,000 chars per line max - increased for SaaS
)

var autoGeneratedExtensions = map[string]bool{
	// SaaS mode: analyze everything - remove .min.js filter for security analysis
}

var autoGeneratedExactFiles = map[string]bool{
	// SaaS mode: analyze everything including lock files
}

// executeAnalyzerSafe wraps analyzer execution with panic recovery
func executeAnalyzerSafe(ctx context.Context, analyzer Analyzer, repo *git.Repository) (result *Result, err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("panic in analyzer %s: %v", analyzer.Name(), r)
		}
	}()

	result, err = analyzer.Analyze(ctx, repo)
	return
}

// isAnalyzable strictly verifies if a file is safe to be read completely into memory
// and parsed by our analysis tools. It prevents OOMs and catastrophic regex backtracking.
func isAnalyzable(fs billy.Filesystem, filePath string) (bool, string) {
	// 1. O(1) Path/Extension checks
	baseName := filepath.Base(filePath)
	if autoGeneratedExactFiles[baseName] {
		return false, "auto-generated file"
	}

	for ext := range autoGeneratedExtensions {
		if strings.HasSuffix(filePath, ext) {
			return false, "auto-generated file"
		}
	}

	// 2. Metadata / O(1) disk check
	info, err := fs.Stat(filePath)
	if err != nil {
		return false, "file missing or inaccessible"
	}

	if info.IsDir() {
		return false, "is a directory"
	}

	if info.Size() > MaxFileSize {
		return false, "file exceeds maximum size limit (10MB)"
	}

	// 3. Content Peeking (O(N) but bounded)
	file, err := fs.Open(filePath)
	if err != nil {
		return false, "failed to open file for peeking"
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	// We might encounter very long lines, allow up to our max explicitly
	buff := make([]byte, MaxLineLength)
	scanner.Buffer(buff, MaxLineLength)

	lineCount := 0
	for scanner.Scan() {
		lineCount++
		if lineCount > MaxLineCount {
			return false, "file exceeds maximum line count (100000)"
		}
	}

	// If scanning fails because token is too long, we caught a minified line!
	if err := scanner.Err(); err == bufio.ErrTooLong {
		return false, "file contains severely minified or elongated lines"
	} else if err != nil {
		// some other read error
		return false, "failed to read lines for validation"
	}

	return true, ""
}
